services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
  server:
    depends_on:
      db:
        condition: service_healthy
    build: "./server"
    ports:
      - 5001:5001
      - 4000:4000
    volumes:
      - ./server/src/:/app/src/
    environment:
      DB_HOST: "db"
  client:
    build: "./client"
    ports:
      - 8080:3000
      - 3000:3000
    volumes:
      - ./client/src/:/app/src/
    environment:
      - REACT_APP_GRAPHQL_API_URL=http://localhost:4000
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
