query GetCitiesWithPlaces {
  getCities {
    name
    places {
      id
      name
      latitude
      longitude
      adress
      website
      picture
      description
      categoryId
    }
  }
}