query GetCitiesWithPlaces {
  getCities {
    name
    id
    places {
      id
      name
      latitude
      longitude
      adress
      website
      picture
      description
      category {
        id
      }
    }
  }
}
