query GetOneCitybyId($getOneCitybyId: String!) {
	getOneCitybyId(id: $getOneCitybyId) {
		id
		name
		picture
		description
		latitude
		longitude
		places {
			id
			name
			latitude
			longitude
			adress
			website
			picture
			description
			category {
				name
				id
				picto
			}
		}
	}
}
