query GetOnePlacebyName($name: String!) {
  getOnePlacebyName(name: $name) {
    id
    name
    latitude
    longitude
    adress
    website
    picture
    description
    category {
      name
      picto
      id
    }
  }
}
