mutation updateManagedCities($userId: Int!, $data: UserManagedCityUpdate!) {
  updateManagedCities(userId: $userId, data: $data) {
    managedCities {
      id
      name
      picture
      description
      latitude
      longitude
    }
  }
}
