mutation UserManagedCityUpdate($userId: Int!, $data: UserManagedCityUpdate!) {
  updateManagedCities(userId: $userId, data: $data) {
    id
    managedCities {
      id
      name
      picture
      latitude
      longitude
    }
  }
}
