mutation UpdatePlace($data: PlaceUpdate!, $updatePlaceId: Float!) {
  updatePlace(data: $data, id: $updatePlaceId) {
    id
    name
    adress
    latitude
    longitude
    picture
    website
    category {
      id
    }
  }
}
